### ISSUE TITLE
API返回的Index在广电机顶盒这一块不能返回id

### ISSUE THREAD

**Issue by backrunner** [irext/index-api#1]
`{"entity":[{"categoryId":3,"cityCode":"110100","operatorId":"8000001","protocol":"philips_rc6","remote":"remote_box_001","remoteMap":"philips_rc6_remote_box_001","status":1,"subCate":1,"priority":999,"binaryMd5":"4c6f0aed6be6d477be94f95aa0f747b0","updateTime":"2016-11-27 11:00:00"},{"categoryId":3,"cityCode":"110100","operatorId":"8000002","protocol":"upd6121g","remote":"remote_box_002","remoteMap":"upd6121g_remote_box_002","status":5,"subCate":1,"priority":999,"binaryMd5":"1a66880b15ca322593c4a9d83db49d6d","updateTime":"2016-11-27 11:00:00"},{"categoryId":3,"cityCode":"110100","operatorId":"262","protocol":"upd6121g","remote":"remote_box_ii_7127","remoteMap":"upd6121g_remote_box_ii_7127","status":1,"subCate":1,"priority":999,"remoteNumber":"7127","binaryMd5":"f8655098b3e7df7d62ff68b3e64518a5","updateTime":"2016-11-27 11:00:00"},{"categoryId":3,"cityCode":"110100","operatorId":"262","protocol":"upd6121g","remote":"remote_box_ii_10687","remoteMap":"upd6121g_remote_box_ii_10687","status":1,"subCate":1,"priority":999,"remoteNumber":"10687","binaryMd5":"fb710d1ebf27e687c97e7f472e297b3a","updateTime":"2016-11-27 11:00:00"},{"categoryId":3,"cityCode":"110100","operatorId":"277","protocol":"upd6121g","remote":"remote_box_ii_7152","remoteMap":"upd6121g_remote_box_ii_7152","status":1,"subCate":1,"priority":1,"remoteNumber":"7152","binaryMd5":"1a66880b15ca322593c4a9d83db49d6d","updateTime":"2016-11-27 11:00:00"},{"categoryId":3,"cityCode":"110100","operatorId":"282","protocol":"upd6121g","remote":"remote_box_ii_7152","remoteMap":"upd6121g_remote_box_ii_7152","status":5,"subCate":1,"priority":1,"remoteNumber":"7152","binaryMd5":"1a66880b15ca322593c4a9d83db49d6d","updateTime":"2016-11-27 11:00:00"},{"categoryId":3,"cityCode":"110100","operatorId":"262","protocol":"philips_rc6","remote":"remote_box_ii_4162","remoteMap":"philips_rc6_remote_box_ii_4162","status":1,"subCate":1,"priority":1,"remoteNumber":"4162","binaryMd5":"1334c9069b7125685331c4dfea41f449","updateTime":"2016-11-27 11:00:00"},{"categoryId":3,"cityCode":"110100","operatorId":"262","protocol":"philips_rc6_26_a6","remote":"remote_box_ii_bj_gehua1","remoteMap":"philips_rc6_26_a6_remote_box_ii_bj_gehua1","status":1,"subCate":1,"priority":50,"remoteNumber":"mi_box_bj_001","binaryMd5":"1d8607a37ada9682357f653680a2e001","updateTime":"2016-11-27 11:00:00"},{"categoryId":3,"cityCode":"110100","operatorId":"262","protocol":"upd6121g","remote":"remote_box_ii_bj_gehua2","remoteMap":"upd6121g_remote_box_ii_bj_gehua2","status":1,"subCate":1,"priority":60,"remoteNumber":"mi_box_bj_002","binaryMd5":"3f8b767ce723d786ffcefc1a7b00e0e8","updateTime":"2016-11-27 11:00:00"}],"status":{"code":0}}`

返回的内容是这样的，并不会返回indexId，以至于不能调用download_bin下载二进制文件

**Comment by strawmanbobi** [comment]
好的，我尽快debug，谢谢。

**Comment by strawmanbobi** [comment]
已经修复此问题。
API或者SDK无需更新，请直接使用。
感谢提出问题。
